name:          Code Guide for @lightburn (Forked from @mdo)
description:   Standards for developing flexible, durable, and sustainable HTML, CSS, and JavaScript.
url:           http://lightburn.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
